[sampler] make backend thread safe
Currently we call `Sample()` in the agent sampler loop and then
`DecayScore` on a ticker in the backend which does concurrent writes
to the `scores` map.

Some agents did panic on prod due to that:
```
fatal error: concurrent map writes

goroutine 10 [running]:
runtime.throw(0xa1b3c0, 0x15)
        /root/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:547 +0x90 fp=0xc820186588 sp=0xc820186570
runtime.mapassign1(0x832540, 0xc82014c6c0, 0xc820186660, 0xc820186658)
        /root/.gimme/versions/go1.6.2.linux.amd64/src/runtime/hashmap.go:445 +0xb1 fp=0xc820186630 sp=0xc820186588
github.com/DataDog/raclette/sampler.(*Backend).DecayScore(0xc82014c6f0)
        /go/src/github.com/DataDog/raclette/sampler/backend.go:95 +0x1a2 fp=0xc8201866d8 sp=0xc820186630
github.com/DataDog/raclette/sampler.(*Backend).Run(0xc82014c6f0)
        /go/src/github.com/DataDog/raclette/sampler/backend.go:57 +0xee fp=0xc8201867a8 sp=0xc8201866d8
github.com/DataDog/raclette/sampler.(*Sampler).Run(0xc82014c720)
        /go/src/github.com/DataDog/raclette/sampler/sampler.go:81 +0x24 fp=0xc8201867b8 sp=0xc8201867a8
runtime.goexit()
        /root/.gimme/versions/go1.6.2.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201867c0 sp=0xc8201867b8
created by main.(*Sampler).Run
        /go/src/github.com/DataDog/raclette/agent/sampler.go:48 +0x6a

```